### ISSUE TITLE
pod crashing every now and then

### ISSUE THREAD

**Issue by vquie** [vantage-sh/helm-charts#14]
We have multiple clusters, all running the vantage agent. Every now and then a pod on any of them crashes. The helm deployment needs to be destroyed and recreated to fix this issue. We are now missing a week of data for some clusters.

```json
{"time":"2023-12-30T11:30:17.665406711Z","level":"INFO","msg":"restoring pod data from backup"}                                                                                                                       
{"time":"2023-12-30T11:30:18.469158454Z","level":"ERROR","msg":"failed to setup data store","err":"unexpected EOF"}
```

How can we solve this issue?

**Comment by macb** [comment]
Hi @vquie, the EOF error causing failures to restart should be addressed in the latest chart version 1.0.22/app version 1.0.17. Your agent is likely being OOMKilled, you can use use `kubectl describe pod` on the agent pod to see what the termination reason is. Assuming they are being OOMKilled, allocate a bit more memory.

**Comment by vquie** [comment]
Hi @macb , why are there default requests and limit values in values.yaml? :-)

I just increased the memory by a lot and updated to the latest version. The error was exactly the same. I recreated the pvc to make it run again. For now this issue does not look as it is solved. I will monitor it closely.

**Comment by macb** [comment]
Hey @vquie, sorry for the slow response. The defaults are there as guidance and so we are good actors in customer's clusters. I'd rather have the agent get OOM'd than cause another pod to get evicted or killed when a customer is first deploying the agent.

After deleting the pvc and updating the agent has the issue occurred again? The fix would not resolve the issue if it had already occured (a bad write to the backup files) but after updating and removing the pvc I would not expect it to occur again.

**Comment by vquie** [comment]
Thanks. After deleting the PVC this time the error did not happen again.
