### ISSUE TITLE
Vantage Agent is crashing 

### ISSUE THREAD

**Issue by riteshsonawane1372** [vantage-sh/helm-charts#3]
![image](https://github.com/vantage-sh/helm-charts/assets/72307121/65e4c89b-6556-492e-a39e-71e21fb17efb)

I did installed the vantage agent using helm. But I don't know it's crashing. You can see the logs in the SS.

**Comment by matthewhembree** [comment]
@riteshsonawane1372 Did it backoff due to OOMKill? You might need to change the resources. This what I had to do.

**Comment by macb** [comment]
Yep, most likely cause of crashing is `OOMKilled`. You should be able to see the reason with:
```
kubectl -n vantage get po vka-vantage-kubernetes-agent-0 -o jsonpath='{.status.containerStatuses[0].lastState.terminated.reason}'
```
You may need to adjust the namespace and pod name to match your specific deployment.

Guidance for resource sizing is available in the [values](https://github.com/vantage-sh/helm-charts/blob/main/charts/vantage-kubernetes-agent/values.yaml#L40-L52).

**Comment by riteshsonawane1372** [comment]
@macb @matthewhembree Thanks for the help. Now vantage pod is running successfully.
